### ISSUE TITLE
Example scss code on utopia.fyi does not generate poper space scale

### ISSUE THREAD

**Issue by sigvei** [trys/utopia-core-scss#2]
This example was generated on utopia.fyi with a single custom step:

```
@use 'node_modules/utopia-core-scss/src/utopia' as utopia;
:root {
  @include utopia.generateSpaceScale((
...
    "customSizes": ("s-l"),
...
  ));
}
```

This will not actually generate the custom size, as the `("s-l")` resolves to a string in scss, making the check in `generateSpaceScale` fail. The solution is to write `"customSizes": ("s-l",)` (with an extra comma).

**Comment by trys** [comment]
Thanks @sigvei! All fixed 😄
