### ISSUE TITLE
Consider using `vw` instead of `vi` for a while

### ISSUE THREAD

**Issue by nachtfunke** [trys/utopia-core-scss#6]
Hello!

I noticed that the clamp function uses logical viewport units, `vi` instead of `vw` https://github.com/trys/utopia-core-scss/blob/main/src/utopia.scss#L13. Support for this unit seems a bit shaky for at least _some_ older browsers.

This is just a suggestion of course, but maybe it would be wise to at least for a while still, use `vw` for a while. In my case, I have to add postprocessing to my build process because I have get rid of this unit.

**Comment by xplosionmind** [comment]
I agree, thanks @nachtfunke!

Scrolling in Firefox on iOS becomes very messy because as the status bar is hidden/displayed the logical viewport size changes, and with it all the contents of the page.

**Comment by nachtfunke** [comment]
What makes this especially nasty is that it is difficult to find out how supported the `vi` unit is. Not even caniuse gives any good answers: https://caniuse.com/viewport-units or https://caniuse.com/viewport-unit-variants

**Comment by trys** [comment]
Hey both - apologies for the delay in responding. There is a "relativeTo" option that can be passed to avoid additional post-processing, but I agree that `vi` isn't stable or supported enough to default to. I've updated the default back to `vw` for now.
